name: Build and Run on Local Mac

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # 👈 This targets your Mac

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t hello-world-app .

    - name: Stop and remove existing container (if any)
      run: |
        docker stop hello-world || true
        docker rm hello-world || true

    - name: Run Docker container
      run: docker run -d --name hello-world -p 3000:3000 hello-world-app

    - name: Done
      run: echo "Hello World app is running on your Mac!"
